### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by carlos22** [condo4/QtSsh#3]
With a GPL license it is not possible to include this in non gpl software. Is this intentional or even required because it is based on a GPL impl (e.g. https://code.qt.io/cgit/qt-creator/qt-creator.git/tree/src/libs/ssh) ?

**Comment by condo4** [comment]
Since it's a libssh2 wrapper, I change the license in BSD (as libssh2), so, you can use it in your project now...
(but if you find Bug, or Improvement, pull request is welcome)

**Comment by carlos22** [comment]
Thanks 👍
