### ISSUE TITLE
how to use "SshScpSend"

### ISSUE THREAD

**Issue by gogoqiu** [condo4/QtSsh#7]
how to use "SshScpSend" please

**Comment by condo4** [comment]
Quick response from my memory, if it's not working, tell me more informations...

firstly you create and connect your SshClient:

SshClient client;
client.connectToHost(.....);
client.waitForState(SshState::Ready);
// Then, you create the SshScpSend object:

SshScpSend *scp = client.getChannel<SshScpSend>("scp_channel"); // scp_channel name is mainly to debug

// Then you can use it:
scp->get("/path/source", "/path/dest");

you can connect signal finished to be notified when it's finished

**Comment by gogoqiu** [comment]
SshScpSend *scp = m_client.getChannel<SshScpSend>("scp_channel"); 
scp->send( this->ui->le_src->text(), this->ui->le_dst->text() );

**Comment by gogoqiu** [comment]
your example(sshgui) can not handshake to win10 openssh server, have a solution to use to the win10 openssh server?
