### ISSUE TITLE
It sounds libssh2 doesn't support ed25519?

### ISSUE THREAD

**Issue by hongnod** [condo4/QtSsh#9]
It sounds libssh2 doesn't support ed25519, is thart correct?

**Comment by condo4** [comment]
Probably depends on the libssh2 version ?https://github.com/libssh2/libssh2/issues/39It seem this feature was merged in 2019 jan after a pull-request from contributors...Not tried my-self...FabienEnvoyé depuis mon smartphone
-------- Message d'origine --------De : hongnod ***@***.***> Date : 14/03/2021  09:58  (GMT+01:00) À : condo4/QtSsh ***@***.***> Cc : Subscribed ***@***.***> Objet : [condo4/QtSsh] It sounds libssh2 doesn't support ed25519? (#9) 
It sounds libssh2 doesn't support ed25519, is thart correct?

**Comment by hongnod** [comment]
Thanks , I got the answer in l"ibssh2/src/openssl.h"

`#if OPENSSL_VERSION_NUMBER >= 0x10101000L && \
!defined(LIBRESSL_VERSION_NUMBER)
# define LIBSSH2_ED25519 1
#else
# define LIBSSH2_ED25519 0
#endif`
